#!/usr/bin/env python3
"""
Submit a single Kalshi create-order request for manual verification.

This script intentionally uses priced limit orders because Kalshi's create-order
API currently requires one explicit side price field.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Any

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.common.buy_execution import KalshiApiBuyClient  # noqa: E402
from scripts.common.market_selection import load_selected_markets  # noqa: E402


def _default_client_order_id(*, ticker: str, side: str) -> str:
    ts = int(time.time() * 1000)
    safe_ticker = "".join(ch for ch in ticker.lower() if ch.isalnum())[:18] or "mkt"
    return f"manual-{safe_ticker}-{side}-{ts}"


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Create one Kalshi buy order")
    parser.add_argument(
        "--ticker",
        default="",
        help="Kalshi market ticker; when omitted, current selected ticker is resolved from discovery output",
    )
    parser.add_argument("--side", required=True, choices=("yes", "no"), help="Contract side to buy")
    parser.add_argument("--count", required=True, type=int, help="Whole contract count")
    parser.add_argument(
        "--price",
        required=True,
        type=float,
        help="Limit price as probability dollars (0.56) or cents (56)",
    )
    parser.add_argument(
        "--time-in-force",
        default="fak",
        choices=("fak", "ioc", "gtc"),
        help="Order time in force",
    )
    parser.add_argument(
        "--client-order-id",
        default="",
        help="Optional custom client_order_id (autogenerated when omitted)",
    )
    parser.add_argument(
        "--base-host",
        default="https://api.elections.kalshi.com",
        help="Kalshi API host",
    )
    parser.add_argument("--config", default="config/run_config.json", help="Run config path for market discovery")
    parser.add_argument("--discovery-output", default="data/market_discovery_latest.json")
    parser.add_argument("--pair-cache", default="data/market_pair_cache.json")
    parser.add_argument(
        "--skip-discovery",
        action="store_true",
        help="Use existing discovery output file and do not refresh current market selection",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what will be sent, without submitting",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    load_dotenv()
    parser = _build_arg_parser()
    args = parser.parse_args(argv)

    if args.count <= 0:
        parser.error("--count must be > 0")

    ticker = str(args.ticker or "").strip()
    if not ticker:
        try:
            selection = load_selected_markets(
                config_path=Path(args.config),
                discovery_output=Path(args.discovery_output),
                pair_cache_path=Path(args.pair_cache),
                run_discovery_first=(not bool(args.skip_discovery)),
            )
        except Exception as exc:
            print(
                json.dumps(
                    {"ok": False, "error_type": type(exc).__name__, "error": f"ticker_resolution_failed:{exc}"},
                    ensure_ascii=True,
                    separators=(",", ":"),
                ),
                file=sys.stderr,
            )
            return 1
        ticker = str((selection.get("kalshi") or {}).get("ticker") or "").strip()
        if not ticker:
            print(
                json.dumps(
                    {"ok": False, "error_type": "RuntimeError", "error": "ticker_resolution_failed:empty_ticker"},
                    ensure_ascii=True,
                    separators=(",", ":"),
                ),
                file=sys.stderr,
            )
            return 1

    client_order_id = str(args.client_order_id).strip() or _default_client_order_id(
        ticker=ticker,
        side=args.side,
    )

    request_preview: dict[str, Any] = {
        "base_host": args.base_host,
        "path": "/trade-api/v2/portfolio/orders",
        "payload_shape": {
            "ticker": ticker,
            "client_order_id": client_order_id,
            "type": "limit",
            "action": "buy",
            "side": args.side,
            "count": int(args.count),
            "time_in_force": args.time_in_force,
            "price_input": float(args.price),
        },
    }
    print(json.dumps({"mode": "preview", "request": request_preview}, ensure_ascii=True, separators=(",", ":")))

    if args.dry_run:
        return 0

    try:
        client = KalshiApiBuyClient(base_host=args.base_host)
        response = client.place_buy_order(
            instrument_id=ticker,
            side=args.side,
            size=float(args.count),
            order_kind="limit",
            limit_price=float(args.price),
            time_in_force=args.time_in_force,
            client_order_id=client_order_id,
        )
    except Exception as exc:
        print(
            json.dumps(
                {
                    "ok": False,
                    "error_type": type(exc).__name__,
                    "error": str(exc),
                    "client_order_id": client_order_id,
                },
                ensure_ascii=True,
                separators=(",", ":"),
            ),
            file=sys.stderr,
        )
        return 1

    print(json.dumps({"ok": True, "result": response}, ensure_ascii=True, separators=(",", ":")))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
